from typing import Tuple, Dict

LANGUAGE_MAPPER: Dict[str, Tuple[str, str]] = {
    'ace_Arab': ('بهسا اچيه', 'Achinese (Arabic)'),
    'ace_Latn': ('Bahsa Acèh', 'Achinese (Latin)'),
    'acm_Arab': ('لهجة عراقية', 'Iraqi Arabic'),
    'acq_Arab': ('لهجة حجازية', 'Hijazi Arabic'),
    'aeb_Arab': ('تونسي', 'Tunisian Arabic'),
    'afr_Latn': ('Afrikaans', 'Afrikaans'),
    'ajp_Arab': ('لهجة شامية', 'South Levantine Arabic'),
    'aka_Latn': ('Akan', 'Akan'),
    'amh_Ethi': ('አማርኛ', 'Amharic'),
    'apc_Arab': ('لهجة شامية', 'North Levantine Arabic'),
    'arb_Arab': ('العربية الفصحى', 'Arabic (Standard)'),
    'ars_Arab': ('لهجة نجدية', 'Najdi Arabic'),
    'ary_Arab': ('الدارجة', 'Moroccan Arabic'),
    'arz_Arab': ('مصرى', 'Egyptian Arabic'),
    'asm_Beng': ('অসমীয়া', 'Assamese'),
    'ast_Latn': ('Asturianu', 'Asturian'),
    'awa_Deva': ('अवधी', 'Awadhi'),
    'ayr_Latn': ('Aymar aru', 'Aymara'),
    'azb_Arab': ('گؤنئی آذربایجان', 'South Azerbaijani'),
    'azj_Latn': ('Azərbaycan', 'North Azerbaijani'),
    'bak_Cyrl': ('Башҡорт теле', 'Bashkir'),
    'bam_Latn': ('Bamanankan', 'Bambara'),
    'ban_Latn': ('Basa Bali', 'Balinese'),
    'bel_Cyrl': ('Беларуская', 'Belarusian'),
    'bem_Latn': ('Ichibemba', 'Bemba'),
    'ben_Beng': ('বাংলা', 'Bengali'),
    'bho_Deva': ('भोजपुरी', 'Bhojpuri'),
    'bjn_Arab': ('بنجار', 'Banjar (Arabic)'),
    'bjn_Latn': ('Bahasa Banjar', 'Banjar (Latin)'),
    'bod_Tibt': ('བོད་སྐད་', 'Tibetan'),
    'bos_Latn': ('Bosanski', 'Bosnian'),
    'bug_Latn': ('Basa Ugi', 'Buginese'),
    'bul_Cyrl': ('Български', 'Bulgarian'),
    'cat_Latn': ('Català', 'Catalan'),
    'ceb_Latn': ('Bisaya', 'Cebuano'),
    'ces_Latn': ('Čeština', 'Czech'),
    'cjk_Latn': ('Chokwe', 'Chokwe'),
    'ckb_Arab': ('سۆرانی', 'Central Kurdish'),
    'crh_Latn': ('Qırımtatarca', 'Crimean Tatar'),
    'cym_Latn': ('Cymraeg', 'Welsh'),
    'dan_Latn': ('Dansk', 'Danish'),
    'deu_Latn': ('Deutsch', 'German'),
    'dik_Latn': ('Thuɔŋjäŋ', 'Dinka'),
    'dyu_Latn': ('Jula', 'Dyula'),
    'dzo_Tibt': ('རྫོང་ཁ', 'Dzongkha'),
    'ell_Grek': ('Ελληνικά', 'Greek'),
    'eng_Latn': ('English', 'English'),
    'epo_Latn': ('Esperanto', 'Esperanto'),
    'est_Latn': ('Eesti', 'Estonian'),
    'eus_Latn': ('Euskara', 'Basque'),
    'ewe_Latn': ('Eʋegbe', 'Ewe'),
    'fao_Latn': ('Føroyskt', 'Faroese'),
    'pes_Arab': ('فارسی', 'Persian'),
    'fij_Latn': ('Na Vosa Vakaviti', 'Fijian'),
    'fin_Latn': ('Suomi', 'Finnish'),
    'fon_Latn': ('Fon gbè', 'Fon'),
    'fra_Latn': ('Français', 'French'),
    'fur_Latn': ('Furlan', 'Friulian'),
    'fuv_Latn': ('Hausa', 'Nigerian Fulfulde'),
    'gla_Latn': ('Gàidhlig', 'Scottish Gaelic'),
    'gle_Latn': ('Gaeilge', 'Irish'),
    'glg_Latn': ('Galego', 'Galician'),
    'grn_Latn': ('Avañe\'ẽ', 'Guarani'),
    'guj_Gujr': ('ગુજરાતી', 'Gujarati'),
    'hat_Latn': ('Kreyòl Ayisyen', 'Haitian Creole'),
    'hau_Latn': ('Hausa', 'Hausa'),
    'heb_Hebr': ('עברית', 'Hebrew'),
    'hin_Deva': ('हिन्दी', 'Hindi'),
    'hne_Deva': ('छत्तीसगढ़ी', 'Chhattisgarhi'),
    'hrv_Latn': ('Hrvatski', 'Croatian'),
    'hun_Latn': ('Magyar', 'Hungarian'),
    'hye_Armn': ('Հայերեն', 'Armenian'),
    'ibo_Latn': ('Asụsụ Igbo', 'Igbo'),
    'ilo_Latn': ('Ilokano', 'Iloko'),
    'ind_Latn': ('Bahasa Indonesia', 'Indonesian'),
    'isl_Latn': ('Íslenska', 'Icelandic'),
    'ita_Latn': ('Italiano', 'Italian'),
    'jav_Latn': ('Basa Jawa', 'Javanese'),
    'jpn_Jpan': ('日本語', 'Japanese'),
    'kab_Latn': ('Taqbaylit', 'Kabyle'),
    'kac_Latn': ('Kachin', 'Jingpho'),
    'kam_Latn': ('Kikamba', 'Kamba'),
    'kan_Knda': ('ಕನ್ನಡ', 'Kannada'),
    'kas_Arab': ('كٲشُر', 'Kashmiri (Arabic)'),
    'kas_Deva': ('कॉशुर', 'Kashmiri (Devanagari)'),
    'kat_Geor': ('ქართული', 'Georgian'),
    'knc_Arab': ('کانوری', 'Kanuri (Arabic)'),
    'knc_Latn': ('Kanuri', 'Kanuri (Latin)'),
    'kaz_Cyrl': ('Қазақ тілі', 'Kazakh'),
    'kbp_Latn': ('Kabɩyɛ', 'Kabiyè'),
    'kea_Latn': ('Kabuverdianu', 'Kabuverdianu'),
    'khm_Khmr': ('ភាសាខ្មែរ', 'Khmer'),
    'kik_Latn': ('Gĩkũyũ', 'Kikuyu'),
    'kin_Latn': ('Ikinyarwanda', 'Kinyarwanda'),
    'kir_Cyrl': ('Кыргыз тили', 'Kyrgyz'),
    'kmb_Latn': ('Kimbundu', 'Kimbundu'),
    'kon_Latn': ('Kikongo', 'Kongo'),
    'kor_Hang': ('한국어', 'Korean'),
    'kmr_Latn': ('Kurmancî', 'Northern Kurdish'),
    'lao_Laoo': ('ລາວ', 'Lao'),
    'lvs_Latn': ('Latviešu', 'Latvian'),
    'lij_Latn': ('Ligure', 'Ligurian'),
    'lim_Latn': ('Lèmburgs', 'Limburgish'),
    'lin_Latn': ('Lingála', 'Lingala'),
    'lit_Latn': ('Lietuvių', 'Lithuanian'),
    'lmo_Latn': ('Lombard', 'Lombard'),
    'ltg_Latn': ('Latgaliešu', 'Latgalian'),
    'ltz_Latn': ('Lëtzebuergesch', 'Luxembourgish'),
    'lua_Latn': ('Tshiluba', 'Luba-Kasai'),
    'lug_Latn': ('Luganda', 'Ganda'),
    'luo_Latn': ('Dholuo', 'Luo'),
    'lus_Latn': ('Mizo ṭawng', 'Mizo'),
    'mag_Deva': ('मगही', 'Magahi'),
    'mai_Deva': ('मैथिली', 'Maithili'),
    'mal_Mlym': ('മലയാളം', 'Malayalam'),
    'mar_Deva': ('मराठी', 'Marathi'),
    'min_Latn': ('Baso Minangkabau', 'Minangkabau'),
    'mkd_Cyrl': ('Македонски', 'Macedonian'),
    'plt_Latn': ('Malagasy', 'Plateau Malagasy'),
    'mlt_Latn': ('Malti', 'Maltese'),
    'mni_Beng': ('মেইতেই লোন', 'Manipuri (Bengali)'),
    'khk_Cyrl': ('Халх', 'Mongolian (Khalkha)'),
    'mos_Latn': ('Mòoré', 'Mossi'),
    'mri_Latn': ('Māori', 'Maori'),
    'zsm_Latn': ('Bahasa Malaysia', 'Standard Malay'),
    'mya_Mymr': ('ဗမာစာ', 'Burmese'),
    'nld_Latn': ('Nederlands', 'Dutch'),
    'nno_Latn': ('Nynorsk', 'Norwegian Nynorsk'),
    'nob_Latn': ('Bokmål', 'Norwegian Bokmål'),
    'npi_Deva': ('नेपाली', 'Nepali'),
    'nso_Latn': ('Sesotho sa Leboa', 'Northern Sotho'),
    'nus_Latn': ('Thok Naath', 'Nuer'),
    'nya_Latn': ('Chichewa', 'Nyanja'),
    'oci_Latn': ('Occitan', 'Occitan'),
    'gaz_Latn': ('Afaan Oromoo', 'Oromo'),
    'ory_Orya': ('ଓଡ଼ିଆ', 'Odia'),
    'pag_Latn': ('Pangasinan', 'Pangasinan'),
    'pan_Guru': ('ਪੰਜਾਬੀ', 'Punjabi'),
    'pap_Latn': ('Papiamentu', 'Papiamento'),
    'pol_Latn': ('Polski', 'Polish'),
    'por_Latn': ('Português', 'Portuguese'),
    'prs_Arab': ('دری', 'Dari'),
    'pbt_Arab': ('پښتو', 'Pashto'),
    'quy_Latn': ('Runasimi', 'Quechua'),
    'ron_Latn': ('Română', 'Romanian'),
    'run_Latn': ('Ikirundi', 'Rundi'),
    'rus_Cyrl': ('Русский', 'Russian'),
    'sag_Latn': ('Sängö', 'Sango'),
    'san_Deva': ('संस्कृतम्', 'Sanskrit'),
    'sat_Beng': ('ᱥᱟᱱᱛᱟᱲᱤ', 'Santali'),
    'scn_Latn': ('Sicilianu', 'Sicilian'),
    'shn_Mymr': ('လိၵ်ႈတႆး', 'Shan'),
    'sin_Sinh': ('සිංහල', 'Sinhala'),
    'slk_Latn': ('Slovenčina', 'Slovak'),
    'slv_Latn': ('Slovenščina', 'Slovenian'),
    'smo_Latn': ('Gagana Samoa', 'Samoan'),
    'sna_Latn': ('ChiShona', 'Shona'),
    'snd_Arab': ('سنڌي', 'Sindhi'),
    'som_Latn': ('Soomaali', 'Somali'),
    'sot_Latn': ('Sesotho', 'Southern Sotho'),
    'spa_Latn': ('Español', 'Spanish'),
    'als_Latn': ('Shqip', 'Albanian'),
    'srd_Latn': ('Sardu', 'Sardinian'),
    'srp_Cyrl': ('Српски', 'Serbian'),
    'ssw_Latn': ('SiSwati', 'Swati'),
    'sun_Latn': ('Basa Sunda', 'Sundanese'),
    'swe_Latn': ('Svenska', 'Swedish'),
    'swh_Latn': ('Kiswahili', 'Swahili'),
    'szl_Latn': ('Ślōnskŏ', 'Silesian'),
    'tam_Taml': ('தமிழ்', 'Tamil'),
    'tat_Cyrl': ('Татарча', 'Tatar'),
    'tel_Telu': ('తెలుగు', 'Telugu'),
    'tgk_Cyrl': ('Тоҷикӣ', 'Tajik'),
    'tgl_Latn': ('Tagalog', 'Tagalog'),
    'tha_Thai': ('ไทย', 'Thai'),
    'tir_Ethi': ('ትግርኛ', 'Tigrinya'),
    'taq_Latn': ('Tamasheq (Latin)', 'Tamasheq (Latin)'),
    'taq_Tfng': ('Tamasheq (Tifinagh)', 'Tamasheq (Tifinagh)'),
    'tpi_Latn': ('Tok Pisin', 'Tok Pisin'),
    'tsn_Latn': ('Setswana', 'Tswana'),
    'tso_Latn': ('Xitsonga', 'Tsonga'),
    'tuk_Latn': ('Türkmen', 'Turkmen'),
    'tum_Latn': ('chiTumbuka', 'Tumbuka'),
    'tur_Latn': ('Türkçe', 'Turkish'),
    'twi_Latn': ('Twi', 'Twi'),
    'tzm_Tfng': ('Tamazight (Tifinagh)', 'Central Atlas Tamazight (Tifinagh)'),
    'uig_Arab': ('ئۇيغۇرچە', 'Uyghur'),
    'ukr_Cyrl': ('Українська', 'Ukrainian'),
    'umb_Latn': ('Umbundu', 'Umbundu'),
    'urd_Arab': ('اردو', 'Urdu'),
    'uzn_Latn': ('Oʻzbekcha', 'Northern Uzbek'),
    'vec_Latn': ('Vèneto', 'Venetian'),
    'vie_Latn': ('Tiếng Việt', 'Vietnamese'),
    'war_Latn': ('Winaray', 'Waray'),
    'wol_Latn': ('Wolof', 'Wolof'),
    'xho_Latn': ('isiXhosa', 'Xhosa'),
    'ydd_Hebr': ('ייִדיש', 'Eastern Yiddish'),
    'yor_Latn': ('Èdè Yorùbá', 'Yoruba'),
    'yue_Hant': ('粵語', 'Cantonese (Traditional)'),
    'zho_Hans': ('中文', 'Chinese (Simplified)'),
    'zho_Hant': ('中文', 'Chinese (Traditional)'),
    'zul_Latn': ('isiZulu', 'Zulu')
}